### ISSUE TITLE
这个是干嘛用的？

### ISSUE THREAD

**Issue by lichifeng** [Jankin-Wu/aoe2-ai-speaker#1]
介绍一下呢？看起来很有意思

**Comment by Jankin-Wu** [comment]
这是为我的帝国时代2弹幕游戏开发的AI语音助手客户端，用户在直播间发送弹幕礼物等事件后会播放相应的语音，AI语音通过调用GPT-SoVITS的API实现，因为最近B站对于互动游戏直播间控制的很严格，需要一些手段增加直播间的活跃，防止被封，目前还在开发中
